---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-proxy.fullname" . }}-config
  labels:
    {{- include "registry-proxy.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    version: 1
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}
    api:
      health:
        listen_address: "0.0.0.0:{{ include "aserto-lib.healthPort" . }}"
      metrics:
        {{- include "aserto-lib.metricsService" . | nindent 8 }}
      service:
        {{- include "registry-proxy.gatewayService" . | nindent 8 }}
        
    remote_registry:
      endpoint: {{ .Values.remoteEndpointURL | required "registry endpoint URL is required" }}
      {{- if .Values.remoteEndpointScheme }}
      scheme: {{.Values.remoteEndpointScheme }}
      {{- end }}
      {{- if .Values.remoteEndpointToken }}
      token: {{.Values.remoteEndpointToken}}
      {{- end}}
        
    nats_listener:
      enabled: false #set to true to enable manifest pushed notifications
    
    cache_settings:
      type: "freecache"
      cache_config:
        freecache_size: 5000000
        ttl: 900000000000 # 15 minutes