apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-proxy.fullname" . }}
  labels:
    {{- include "registry-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ include "aserto-lib.httpPort" . }}
      targetPort: http
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
    - name: metrics
      port: {{ include "aserto-lib.metricsPort" . }}
      targetPort: metrics
  selector:
    {{- include "registry-proxy.selectorLabels" . | nindent 4 }}
