---
apiVersion: apps/v1
kind: {{ include "topaz.appKind" . }}
metadata:
  name: {{ include "topaz.fullname" . }}
  labels:
    {{- include "topaz.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "topaz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "topaz.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "topaz.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ (.Values.ports).grpc | default "8282" }}
              protocol: TCP
            - name: http
              containerPort: {{ (.Values.ports).https | default "8383" }}
              protocol: TCP
            - name: health
              containerPort: {{ (.Values.ports).health | default "8484" }}
              protocol: TCP
            {{- if (.Values.metrics).enabled }}
            - name: metrics
              containerPort: {{ (.Values.ports).metrics | default "8585" }}
              protocol: TCP
            {{- end }}
          startupProbe:
            grpc:
              port: {{ (.Values.ports).health | default "8484" }}
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            grpc:
              port: {{ (.Values.ports).health | default "8484" }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            grpc:
              port: {{ (.Values.ports).health | default "8484" }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: db
              mountPath: /db
              readOnly: false
            - name: decisions
              mountPath: /decisions
              readOnly: false
            - name: opa
              mountPath: /opa-persistence
              readOnly: false
          {{- if (.Values.tls).grpc }}
            - name: grpc-certs
              mountPath: /grpc-certs
              readOnly: true
          {{- end }}
          {{- if (.Values.tls).https }}
            - name: https-certs
              mountPath: /https-certs
              readOnly: true
          {{- end }}
          {{- with (.Values.directory).remote -}}
            {{ include "topaz.remoteDirectoryCertVolumeMount" . | nindent 12 }}
          {{- end }}
          {{- if (.Values.decisionLogs).remote }}
            - name: scribe-cert
              mountPath: /scribe-cert
          {{- end }}
          {{- if (.Values.controller).enabled }}
            - name: controller-cert
              mountPath: /controller-cert
          {{- end }}
            {{- with .Values.volumeMounts -}}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: TOPAZ_CFG_DIR
              value: /config
          {{- with ((.Values.directory).remote).apiKeySecret -}}
            {{ include "topaz.remoteDirectoryKeyEnv" . | nindent 12 }}
          {{- end }}
          {{- with (.Values.auth).apiKeys -}}
            {{ include "topaz.apiKeysEnv" . | nindent 12 }}
          {{- end }}
          {{- with (((.Values.directory).edge).sync).apiKeySecret -}}
            {{ include "topaz.edgeKeyEnv" . | nindent 12 }}
          {{- end }}
          {{- with (((.Values.opa).policy).discovery).apiKeySecret -}}
            {{ include "topaz.discoveryKeyEnv" . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "topaz.fullname" . }}-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- with (.Values.tls).grpc }}
        - name: grpc-certs
          secret:
            secretName: {{ . }}
      {{- end }}
      {{- with (.Values.tls).https }}
        - name: https-certs
          secret:
            secretName: {{ . }}
      {{- end }}
      {{- if ((.Values.directory).remote).address -}}
        {{ include "topaz.remoteDirectoryCertVolume" . | nindent 8 }}
      {{- end }}
        - name: db
        {{- if empty (.Values.directory).remote | and (((.Values.directory).edge).persistence).enabled }}
          persistentVolumeClaim:
            claimName: {{ include "topaz.fullname" . }}-pvc-db
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: opa
        {{- if ((.Values.opa).persistence).enabled }}
          persistentVolumeClaim:
            claimName: {{ include "topaz.fullname" . }}-pvc-policy
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: decisions
        {{- if (.Values.decisionLogs).enabled | and ((.Values.decisionLogs).persistence).enabled }}
          persistentVolumeClaim:
            claimName: {{ include "topaz.fullname" . }}-pvc-decisions
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if (.Values.decisionLogs).remote -}}
        {{- include "topaz.scribeCertVolume" . | nindent 8 }}
      {{- end -}}
      {{- if (.Values.controller).enabled -}}
        {{- include "topaz.controllerCertVolume" .| nindent 8 }}
      {{- end -}}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
