{{- with (.Values.opa).persistence }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "topaz.fullname" $ }}-pvc-policy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storage | default "10Mi" }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  {{- if .selector }}
  selector:
    {{- .selector | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

