{{- with .Values.controller }}
{{- if .enabled | and .mtlsCert }}
{{- if empty .mtlsKey }}
  {{- fail "controller requires either mtlsCertSecretName or mtlsCert and mtlsKey" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topaz.fullname" $ }}-controller-client-cert
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- .mtlsCert |  nindent 4 }}
  tls.key: |
    {{- .mtlsKey | nindent 4 }}
{{- end }}
{{- end }}
