{{- with ((.Values.decisionLogs).remote).scribe }}
{{- if .mtlsCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topaz.fullname" $ }}-scribe-client-cert
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- .mtlsCert |  nindent 4 }}
  tls.key: |
    {{- .mtlsKey | nindent 4 }}
{{- end }}
{{- end }}
