---
apiVersion: v2
name: aserto
description: A Helm chart for Kubernetes
icon: https://www.aserto.com/images/aserto-logo.png

maintainers:
  - name: Aserto
    url: https://github.com/aserto-dev

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: aserto-lib
    version: 0.2.0
    repository: file://../aserto-lib
  - name: authorizer
    version: 0.2.0
    repository: file://../authorizer
    condition: authorizer.enabled
  - name: controller
    version: 0.0.1
    repository: file://../controller
  - name: console
    version: 0.1.7
    repository: file://../console
    condition: console.enabled
  - name: directory
    version: 0.2.0
    repository: file://../directory
  - name: discovery
    version: 0.2.0
    repository: file://../discovery
    condition: discovery.enabled
  - name: multi-tenant-scim
    version: 0.0.1
    repository: file://../multi-tenant-scim
    condition: multi-tenant-scim.enabled
  - name: registry-proxy
    version: 0.1.0
    repository: file://../registry-proxy
    condition: registry-proxy.enabled
  - name: scim
    version: 0.2.0
    repository: file://../scim
    condition: scim.enabled
