apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authorizer.fullname" . }}
  labels:
    {{- include "authorizer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authorizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "authorizer.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "aserto-lib.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "authorizer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "authorizer.fullname" . }}-config
            items:
              - key: config.yaml
                path: config.yaml

        {{- with (include "aserto-lib.grpcConfig" . | fromYaml).certSecret }}
        - name: grpc-certs
          secret:
            secretName: {{ . }}
        {{- end }}

        {{- with (include "aserto-lib.httpConfig" . | fromYaml).certSecret }}
        - name: tls-certs
          secret:
            secretName: {{ . }}
        {{- end }}

        {{- with ((include "aserto-lib.controllerClientCfg" . | fromYaml).caCertSecret).name }}
        - name: controller-grpc-certs
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}

        {{- with (include "aserto-lib.discoveryCfg" . | fromYaml).tlsCertSecret }}
        - name: discovery-tls-certs
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["run", "--config-file", "/config/config.yaml"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- with (include "aserto-lib.selfPorts" . | fromYaml )}}
            - name: http
              containerPort: {{ .http }}
            - name: grpc
              containerPort: {{ .grpc }}
            - name: metrics
              containerPort: {{ .metrics }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true

          {{- with (include "aserto-lib.grpcConfig" . | fromYaml).certSecret }}
            - name: grpc-certs
              mountPath: /grpc-certs
              readOnly: true
          {{- end }}

          {{- with (include "aserto-lib.httpConfig" . | fromYaml).certSecret }}
            - name: tls-certs
              mountPath: /tls-certs
              readOnly: true
          {{- end }}

          {{- with ((include "aserto-lib.controllerClientCfg" . | fromYaml).caCertSecret).name }}
            - name: controller-grpc-certs
              mountPath: /controller-grpc-certs
              readOnly: true
          {{- end }}

          {{- if (include "aserto-lib.discoveryCfg" . | fromYaml).tlsCertSecret }}
            - name: discovery-tls-certs
              mountPath: /discovery-tls-certs
              readOnly: true
          {{- end }}
          env:
          {{- with include "aserto-lib.controllerKeyEnv" (list . "read") }}
            - name: AUTHORIZER_DS0_API_KEY
              {{- . | nindent 14 }}
          {{- end }}

          {{- with .Values.apiKey }}
            - name: AUTHORIZER_ROOT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
          {{- end }}

          {{- with include "aserto-lib.directoryKeyEnv" (list . "read") }}
            - name: AUTHORIZER_REMOTE_DIRECTORY_API_KEY
              {{- . | nindent 14 }}
          {{- end }}

          {{- with (include "aserto-lib.discoveryApiKey" . | fromYaml) }}
            - name: AUTHORIZER_DISCOVERY_ROOT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
          {{- end }}
        {{- with (include "aserto-lib.selfPorts" . | fromYaml )}}
          livenessProbe:
            grpc:
              port: {{ .health }}
          readinessProbe:
            grpc:
              port: {{ .health }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
