---
{{- $secretName := include "scim.auth.secretName" . -}}
{{- $secretKey := include "scim.auth.secretKey" . -}}
{{- $data :=  (lookup "v1" "Secret" .Release.Namespace $secretName).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  {{- if $data }}
  {{ $secretKey }}: {{ get $data $secretKey }}
  {{- else }}
  {{ $secretKey }}: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
