---
{{- $secretName := include "scim.auth.secretName" . -}}
{{- $secretKey := include "scim.auth.secretKey" . -}}
{{- $secret :=  lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if empty $secret | or (include "aserto-lib.isManagedResource" (list $secret .Release.Name) | eq "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
{{- if ($secret).data }}
  {{ $secretKey }}: {{ get $secret.data $secretKey }}
{{- else }}
  {{ $secretKey }}: {{ randAlphaNum 20 | b64enc }}
{{- end }}

{{- end }}
