---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scim.fullname" . }}-config
  labels:
    {{- include "scim.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    server:
      listen_address: ":{{ include "scim.port" . }}"
    {{- with .Values.certSecret -}}
      certs:
        tls_key_path: '/https-certs/tls.key'
        tls_cert_path: '/https-certs/tls.crt'
        tls_ca_cert_path: '/https-certs/ca.crt'
    {{- end }}
      auth:
        basic:
          enabled: {{ ((.Values.auth).basic).enabled | default "true" }}
          username: {{ ((.Values.auth).basic).username | default "scim" }}
        bearer:
          enabled: {{ ((.Values.auth).bearer).enabled | default "true" }}
    directory:
      {{- include "aserto-lib.controllerClient" . | nindent 6 }}
    scim:
      create_email_identities: {{ .Values.createEmailIdentities | default "true" }}
      create_role_groups: {{ .Values.createRoleGroups | default "false" }}
      user_object_type: {{ .Values.userObjectType | default "user" }}
      identity_object_type: {{ .Values.identityObjectType | default "identity" }}
      identity_relation: {{ .Values.identityRelation | default "identifier" }}
      group_object_type: {{ .Values.groupObjectType | default "group" }}
      group_member_relation: {{ .Values.groupMemberRelation | default "member" }}
      group_mappings:
        {{- .Values.groupMappings | default list | toYaml | nindent 8 }}
      user_mappings:
        {{- .Values.userMappings | default list | toYaml | nindent 8 }}
