---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scim.fullname" . }}-config
  labels:
    {{- include "scim.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    server:
      listen_address: ":{{ include "scim.port" . }}"
    {{- with .Values.certSecret -}}
      certs:
        tls_key_path: '/tls-certs/tls.key'
        tls_cert_path: '/tls-certs/tls.crt'
        tls_ca_cert_path: '/tls-certs/ca.crt'
    {{- end }}
      auth:
        basic:
          enabled: {{ ((.Values.auth).basic).enabled | default "true" }}
          username: {{ ((.Values.auth).basic).username | default "scim" }}
        bearer:
          enabled: {{ ((.Values.auth).bearer).enabled | default "true" }}
    directory:
      {{- include "aserto-lib.controllerClient" . | nindent 6 }}
    scim:
      user:
        object_type: {{ .Values.user.objectType | default "user" }}
        identity_object_type: {{ .Values.user.identityObjectType | default "identity" }}
        identity_relation: {{ .Values.user.identityRelation | default "user#identifier" }}
        property_mapping:
          {{- .Values.user.propertyMapping | default list | toYaml | nindent 10 }}
        source_object_type: {{ .Values.user.sourceObjectType | default "scim_user" }}
        manager_relation: {{ .Values.user.managerRelation | default "manager" }}
      group:
        object_type: {{ .Values.group.objectType | default "group" }}
        group_member_relation: {{ .Values.group.groupMemberRelation | default "member" }}
        source_object_type: {{ .Values.group.sourceObjectType | default "scim_group" }}
      role:
        object_type: {{ .Values.role.objectType | default "group" }}
        role_relation: {{ .Values.role.roleRelation | default "member" }}
      relations:
        {{- .Values.relations | default list | toYaml | nindent 8 }}
