apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scim.fullname" . }}
  labels:
    {{- include "scim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scim.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "aserto-lib.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "scim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "scim.fullname" . }}-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.certSecret }}
        - name: https-certs
          secret:
            secretName: {{ . }}
      {{- end }}

      {{- with ((include "aserto-lib.controllerClientCfg" . | fromYaml).caCertSecret).name }}
        - name: root-ds-grpc-certs
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: ca.crt
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["run", "--config", "/config/config.yaml"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: scim
              containerPort: {{ include "scim.port" . }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          {{- with .Values.certSecret }}
            - name: https-certs
              mountPath: /https-certs
              readOnly: true
          {{- end }}
          {{- with ((include "aserto-lib.controllerClientCfg" . | fromYaml).caCertSecret).name }}
            - name: root-ds-grpc-certs
              mountPath: /root-ds-grpc-certs
              readOnly: true
          {{- end }}
          env:
            - name: ASERTO_SCIM_SERVER_AUTH_BASIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "scim.auth.secretName" . }}
                  key: {{ include "scim.auth.secretKey" . }}
            - name: ASERTO_SCIM_SERVER_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "scim.auth.secretName" . }}
                  key: {{ include "scim.auth.secretKey" . }}
            {{- with (include "aserto-lib.controllerApiKeyEnv" . | fromYaml) }}
            - name: ASERTO_SCIM_DIRECTORY_API_KEY
              {{ . | toYaml | nindent 14 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
