apiVersion: v1
kind: Service
metadata:
  name: {{ include "scim.fullname" . }}
  labels:
    {{- include "scim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: scim
      port: {{ include "scim.port" . }}
      targetPort: scim
  selector:
    {{- include "scim.selectorLabels" . | nindent 4 }}
