---
global:
  aserto:
    oidc:
      domain: oidc_domain
      audience: oidc_audience
console:
  authorizerURL: https://authorizer.aserto.example.com
  directoryURL: https://directory.aserto.example.com
discovery:
  registries:
    ghcr.io:
      scheme: bearer
      tokenSecretName: ghcr-token-secret
directory:
  rootDirectory:
    database:
      host: root-db-host
  tenantDirectory:
    database:
      host: tenant-db-host
  sshAdminKeys:
    keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDf6
