---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multi-tenant-scim.fullname" . }}-config
  labels:
    {{- include "multi-tenant-scim.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    server:
      listen_address: ":{{ include "multi-tenant-scim.port" . }}"
      certs:
        tls_key_path: '/https-certs/tls.key'
        tls_cert_path: '/https-certs/tls.crt'
        tls_ca_cert_path: '/https-certs/ca.crt'
      auth:
        basic:
          enabled: {{ ((.Values.auth).basic).enabled | default "true" }}
          username: {{ ((.Values.auth).basic).username | default "multi-tenant-scim" }}
        bearer:
          enabled: {{ ((.Values.auth).bearer).enabled | default "true" }}
    directory:
      {{- include "aserto-lib.rootDirectoryClient" . | nindent 6 }}
