apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi-tenant-scim.fullname" . }}
  labels:
    {{- include "multi-tenant-scim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "multi-tenant-scim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multi-tenant-scim.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "aserto-lib.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "multi-tenant-scim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "multi-tenant-scim.fullname" . }}-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: tls-certs
          {{- with (include "aserto-lib.httpConfig" . | fromYaml) }}
          {{- if .certSecret }}
          secret:
            secretName: {{ .certSecret }}
          {{- else }}
          emptyDir: {}
          {{- end }}
          {{- end }}

       {{- with ((include "aserto-lib.controllerClient" . | fromYaml).caCertSecret).name }}
        - name: controller-grpc-certs
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["run", "--config", "/config/config.yaml"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mtscim
              containerPort: {{ include "multi-tenant-scim.port" . }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- with .Values.certSecret }}
            - name: tls-certs
              mountPath: /tls-certs
              readOnly: true
            {{- end }}
            {{- with ((include "aserto-lib.directoryClientCfg" . | fromYaml).caCertSecret).name }}
            - name: directory-grpc-certs
              mountPath: /directory-grpc-certs
              readOnly: true
            {{- end }}
            {{- with ((include "aserto-lib.controllerClientCfg" . | fromYaml).caCertSecret).name }}
            - name: controller-grpc-certs
              mountPath: /controller-grpc-certs
              readOnly: true
            {{- end }}
          env:
            {{- with include "aserto-lib.controllerKeyEnv" (list . "readStore") }}
            - name: ASERTO_SCIM_CONTROLLER_API_KEY
              {{ . | nindent 14 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
