apiVersion: v1
kind: Service
metadata:
  name: {{ include "authorizer.fullname" . }}
  labels:
    {{- include "authorizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ include "aserto-lib.httpsPort" . }}
      targetPort: https
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
  selector:
    {{- include "authorizer.selectorLabels" . | nindent 4 }}
