---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directory.fullname" . }}-config
  labels:
    {{- include "directory.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    api:
      grpc:
        {{- include "aserto-lib.grpcService" . | nindent 8 }}
      gateway:
        {{- include "aserto-lib.httpsService" . | nindent 8 }}
      health:
        listen_address: 0.0.0.0:{{ include "aserto-lib.healthPort" . }}
      metrics:
        {{- include "aserto-lib.metricsService" . | nindent 8 }}

    {{ if .Values.rootDirectory.runService }}
    {{- with .Values.rootDirectory.database -}}
    root_db:
      writer:
        host: "{{ .host | required ".Values.rootDirectory.database.host is required." }}"
        port: {{ .port | default "5432" }}
        db_name: {{  .dbName | default "aserto-root-ds" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .admin.user | default "postgres" }}
        {{- if .admin.options -}}
        {{ toYaml .admin.options | nindent 8 }}
        {{ end }}
      reader:
        host: "{{ .host | required ".Values.rootDirectory.database.host is required." }}"
        port: {{ .port | default 5432 }}
        db_name: {{ .dbName | default "aserto-root-ds" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .reader.user | default "root_reader" }}
        {{- if .reader.options -}}
        {{ toYaml .reader.options | nindent 8 }}
        {{ end }}
    {{- end }}
    {{- end }}

    {{ if .Values.tenantDirectory.runService }}
    {{- with .Values.tenantDirectory.database -}}
    db:
      writer:
        host: "{{ .host | required ".Values.tenantDirectory.host is required." }}"
        port: {{ .port | default 5432 }}
        db_name: {{ .dbName | default "aserto-ds" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .admin.user | default "postgres" }}
        {{- if .admin.options -}}
        {{ toYaml .admin.options | nindent 8 }}
        {{ end }}
      reader:
        host: "{{ .host | required ".Values.tenantDirectory.host is required." }}"
        port: {{ .port | default 5432 }}
        db_name: {{ .dbName | default "aserto-ds" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .reader.user | default "tenant_reader" }}
        {{- if .reader.options -}}
        {{ toYaml .reader.options | nindent 8 }}
        {{ end }}
    {{- end }}
    {{- end }}

    root_ds:
      client:
        {{- include "aserto-lib.rootDirectoryClient" . | nindent 8 }}

      {{- if and .Values.rootDirectory.runService .Values.rootDirectory.manifest }}
      root_manifest: {{ .Values.rootDirectory.manifest }}
      {{- end }}

    nats:
      {{- if .Values.nats }}
      {{ toYaml .Values.nats | nindent 6 }}
      {{- else }}
      enabled: false
      {{- end }}

    cache:
      {{- $cache := .Values.cache | default dict }}
      cache_size_mb: {{ $cache.sizeMB | default 25 }}
      cache_invalidation_time_seconds: {{ $cache.ttlSeconds | default 1800 }}
      clean_window_seconds: {{ $cache.cleanWindowSeconds | default 10 }}

    authorization:
      {{- if .Values.noAuthorization }}
      disable: true
      {{- else }}
      bypass:
        - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
        - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
      {{- if .Values.rootDirectory.runService }}
      bypass_tenants:
        - {{ include "aserto-lib.rootDirectoryTenantID" . }}
      {{- end }}
      {{- end }}

    authentication:
      authenticators_enabled:
        root_key: true
        oidc: true
        {{- if (.Values.authentication).machineAccounts }}
        machine_account: true
        {{- end }}

      root_keys:
        {{- if .Values.tenantDirectory.runService }}
        keys:
          - key: ${DIRECTORY_DS_WRITE_KEY}
            account: root-key-directory-writer@aserto.com
          - key: ${DIRECTORY_DS_READ_KEY}
            account: root-key-directory-reader@aserto.com

        {{- if .Values.rootDirectory.runService }}
        tenant_overrides:
          {{ include "aserto-lib.rootDirectoryTenantID" .}}:
            - key: ${DIRECTORY_ROOT_DS_CLIENT_API_KEY}
              account: "root-ds"
        {{- end }}

        {{- else }}
        keys:
          - key: ${DIRECTORY_ROOT_DS_CLIENT_API_KEY}
            account: "root-ds"
        {{- end }}

      oidc:
        {{- include "aserto-lib.oidcConfig" . | nindent 8 }}

      override:
        - methods:
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
          - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
          authenticators_enabled:
            anonymous: true

