---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootDirectory.database.reader.credentialsSecret }}
data:
  {{- $data := (lookup "v1" "Secret" .Release.Namespace .Values.rootDirectory.database.reader.credentialsSecret).data }}
  {{- if $data }}
  username: {{ $data.username }}
  password: {{ $data.password }}
  {{- else }}
  username: {{ "root_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc}}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenantDirectory.database.reader.credentialsSecret }}
data:
  {{- $data := (lookup "v1" "Secret" .Release.Namespace .Values.tenantDirectory.database.reader.credentialsSecret).data }}
  {{- if $data }}
  username: {{ $data.username }}
  password: {{ $data.password }}
  {{- else }}
  username: {{ "tenant_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
