global:
  aserto:
    oidc:
      domain: ""
      audience: ""

    ports:
      grpc: 8282
      https: 8383
      health: 8484
      mertics: 8585

    grpc:
      connectionTimeoutSec: 2

    # https:
    #   read_timeout: 2s
    #   read_header_timeout: 2s
    #   write_timeout: 2s
    #   idle_timeout: 30s
    #   allowed_origins:
    #     - https://*.example.com

    metrics:
      zpages: true

    rootDirectory:
      disableTLSVerification: true
      tenantID: 06e1fdac-0676-11ef-b77e-0005a79d9368
    directory:
      disableTLSVerification: true

# directory:
#   rootDirectory:
#     database:
#       host: ""
#       port: 5432
#       sslMode: require

#   tenantDirectory:
#     database:
#       host: ""
#       port: 5432
#       sslMode: require

# scim:
#   auth:
#     secretName: scim-password
#     secretKey: password
#     basic:
#       enabled: true
#       username: scim
#     bearer:
#       enabled: true

#   createEmailIdentities: true
#   createRoleGroups: false
#   userObjectType: user
#   identityObjectType: identity
#   identityRelation: identifier
#   groupObjectType: group
#   groupMemberRelation: memeber
#   groupMappings: []
#   userMappings: []
