{{- with (.Values.sshAdminKeys).keys -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directory.adminKeysConfigMapName" $ }}
data:
  {{ include "directory.adminKeysConfigMapKey" $ }}: |
    {{- . | nindent 4 }}
{{- end -}}
