---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directory.fullname" . }}-admin-keys
data:
  authorized_keys: |
    {{- .Values.sshAdminKeys | required  "sshAdminKeys is required" | nindent 4 }}

