{{- $cfg := include "aserto-lib.directoryApiKeys" . | fromYaml -}}
{{- $secret :=  lookup "v1" "Secret" .Release.Namespace $cfg.secretName }}
{{- if empty $secret | or
    (include "aserto-lib.isManagedResource" (list $secret .Release.Name) | eq "true")
-}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cfg.secretName }}
data:
{{- if ($secret).data }}
  {{ $cfg.writerKey }}: {{ get $secret.data $cfg.writerKey }}
  {{ $cfg.readerKey }}: {{ get $secret.data $cfg.readerKey }}
{{- else }}
  {{ $cfg.writerKey }}: {{ randAlphaNum 20 | b64enc }}
  {{ $cfg.readerKey }}: {{ randAlphaNum 20 | b64enc }}
{{- end }}
{{- end }}
