---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directory.fullname" . }}-config
  labels:
    {{- include "directory.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    api:
      grpc:
        {{- include "aserto-lib.grpcService" . | nindent 8 }}
      gateway:
        {{- include "aserto-lib.httpsService" . | nindent 8 }}
      health:
        listen_address: 0.0.0.0:{{ include "aserto-lib.healthPort" . }}
      metrics:
        {{- include "aserto-lib.metricsService" . | nindent 8 }}
      admin:
        authorized_keys_path: /admin-keys/{{ include "directory.adminKeysConfigMapKey" . }}

  {{- with .Values.database }}
    db:
      writer:
        host: "{{ .host | required ".Values.database.host is required." }}"
        port: {{ .port | default 5432 }}
        db_name: {{ .dbName | default "aserto-directory" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .admin.user | default "postgres" }}
      {{- if .admin.options -}}
        {{ toYaml .admin.options | nindent 8 }}
      {{ end }}
      reader:
        host: "{{ .host | required ".Values.database.host is required." }}"
        port: {{ .port | default 5432 }}
        db_name: {{ .dbName | default "aserto-directory" }}
        ssl_mode: {{ .sslMode | default "require" }}
        user: {{ .reader.user | default "directory_reader" }}
      {{- if .reader.options -}}
        {{ toYaml .reader.options | nindent 8 }}
      {{ end }}
  {{- end }}

  {{- if not (include "directory.isStandalone" .) }}
    root_ds:
      client:
        {{- include "aserto-lib.controllerClient" . | nindent 8 }}
  {{- end }}

    nats:
    {{- if .Values.nats }}
      {{ toYaml .Values.nats | nindent 6 }}
    {{- else }}
      enabled: false
    {{- end }}

    cache:
      {{- $cache := .Values.cache | default dict }}
      cache_size_mb: {{ $cache.sizeMB | default 128 }}
      cache_invalidation_time_seconds: {{ $cache.ttlSeconds | default 1800 }}
      clean_window_seconds: {{ $cache.cleanWindowSeconds | default 10 }}

    authorization:
  {{- if include "directory.isStandalone" . }}
      disable: true
  {{- else }}
      bypass:
        - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
        - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
  {{- end }}

    authentication:
      authenticators_enabled:
        root_key: true

      {{- with include "aserto-lib.oidcConfig" . }}
        oidc: true
      {{- end }}

      {{- if (.Values.authentication).machineAccounts }}
        machine_account: true
      {{- end }}

      root_keys:
        keys:
          - key: ${DIRECTORY_DS_WRITE_KEY}
            account: root-key-directory-writer@aserto.com
          - key: ${DIRECTORY_DS_READ_KEY}
            account: root-key-directory-reader@aserto.com
          - key: ${DIRECTORY_ROOT_DS_CLIENT_API_KEY}
            account: root-key-directory-store-writer@aserto.com


    {{- with include "aserto-lib.oidcConfig" . }}
      oidc:
        {{- . | nindent 8 }}
    {{- end }}

      override:
        - methods:
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
          - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
          authenticators_enabled:
            anonymous: true
