{{- $rootData := (lookup "v1" "Secret" .Release.Namespace .Values.rootDirectory.database.reader.credentialsSecret).data -}}
{{- if empty $rootData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootDirectory.database.reader.credentialsSecret }}
data:
  username: {{ "root_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc}}
{{- end }}

{{- $tenantData := (lookup "v1" "Secret" .Release.Namespace .Values.tenantDirectory.database.reader.credentialsSecret).data -}}
{{- if empty $tenantData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenantDirectory.database.reader.credentialsSecret }}
data:
  username: {{ "tenant_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
{{- end }}
