---
{{- $rootSecret := lookup "v1" "Secret" .Release.Namespace .Values.rootDirectory.database.reader.credentialsSecret | default dict -}}
{{- if empty $rootSecret | or (include "aserto-lib.isManagedResource" (list $rootSecret .Release.Name) | eq "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootDirectory.database.reader.credentialsSecret }}
data:
{{- if ($rootSecret).data }}
  username: {{ $rootSecret.data.username }}
  password: {{ $rootSecret.data.password }}
{{- else }}
  username: {{ "root_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc}}
{{- end }}

{{- end }}
---
{{- $tenantSecret := lookup "v1" "Secret" .Release.Namespace .Values.tenantDirectory.database.reader.credentialsSecret }}
{{- if empty $tenantSecret | or (include "aserto-lib.isManagedResource" (list $tenantSecret .Release.Name) | eq "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenantDirectory.database.reader.credentialsSecret }}
data:
{{- if ($tenantSecret).data }}
  username: {{ $tenantSecret.data.username }}
  password: {{ $tenantSecret.data.password }}
{{- else }}
  username: {{ "tenant_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
{{- end }}

{{- end }}
