{{- if .Values.ingress.enabled -}}
{{- $fullName := include "directory.fullname" . -}}
---
{{- with .Values.ingress.http }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "directory.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $host := include "aserto-lib.ingressHost" (list $ .) }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-http
                port:
                  name: http
  {{- with .tlsSecret }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ . }}
  {{- end }}
{{- end }}
---
{{- with .Values.ingress.grpc }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "directory.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $host := include "aserto-lib.ingressHost" (list $ .) }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-grpc
                port:
                  name: grpc
  {{- with .tlsSecret }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}

