{{- if .Values.rootDirectory.runService }}
{{- $cfg := include "aserto-lib.rootClientCfg" . | fromYaml -}}
{{- $secretName := ($cfg.apiKeySecret).name | default "root-ds-keys" -}}
{{- $secretKey := ($cfg.apiKeySecret).key | default "api-key" -}}

{{- $apiKey := $cfg.apiKey -}}
{{- if empty $apiKey -}}
  {{- $secret :=  lookup "v1" "Secret" $.Release.Namespace $secretName }}
  {{- if empty $secret }}
    {{- $apiKey = randAlphaNum 32 | b64enc }}
  {{- else if (include "aserto-lib.isManagedResource" (list $secret .Release.Name) | toYaml) -}}
    {{- $apiKey = get ($secret).data $secretKey }}
  {{- end }}
{{- end -}}

{{- with $apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  {{ $secretKey }}: {{ . }}
{{- end }}

{{- end }}
