---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "directory.fullname" . }}-http
  labels:
    {{- include "directory.labels" . | nindent 4 }}

  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ include "aserto-lib.httpPort" . }}
      targetPort: http
    - name: metrics
      port: {{ include "aserto-lib.metricsPort" . }}
      targetPort: metrics
  selector:
    {{- include "directory.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "directory.fullname" . }}-grpc
  labels:
    {{- include "directory.labels" . | nindent 4 }}

  {{- with .Values.service.grpc.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.grpc.type }}
  ports:
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
  selector:
    {{- include "directory.selectorLabels" . | nindent 4 }}
