---
{{- $cfg := .Values.apiKey -}}
{{- if empty (lookup "v1" "Secret" .Release.Namespace $cfg.secretName).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cfg.secretName }}
data:  
  {{ $cfg.secretKey }}: {{ randAlphaNum 20 | b64enc }}  
{{- end }}