---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery.fullname" . }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}

  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ include "aserto-lib.httpPort" . }}
      targetPort: http
    {{- if not .Values.ingress.enabled }}
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
    {{- end }}
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}

{{- if .Values.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery.fullname" . }}-grpc
  labels:
    {{- include "discovery.labels" . | nindent 4 }}

  {{- with .Values.service.grpc.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.grpc.type }}
  ports:
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}
{{- end }}

