---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discovery.fullname" . }}-config
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.logLevel | default "info" }}

    api:
      grpc:
        {{- include "aserto-lib.grpcService" . | nindent 8 }}
      gateway:
        {{- include "aserto-lib.httpsService" . | nindent 8 }}
      health:
        listen_address: 0.0.0.0:{{ include "aserto-lib.healthPort" . }}
      metrics:
        {{- include "aserto-lib.metricsService" . | nindent 8 }}

    nats_listener:
      enabled: false

    bundle_defaults:
      {{- include "discovery.bundleDefaults" . | nindent 6 }}

    cache_settings:
      {{- include "discovery.cacheSettings" . | nindent 6 }}

    registries:
      {{- include "discovery.registriesConfig" . | nindent 6 }}

    ds0:
      {{- include "aserto-lib.rootDirectoryClient" . | nindent 6 }}

    authentication:
      authenticators_enabled:
        root_key: true
        oidc: true

      oidc:
        {{- include "aserto-lib.oidcConfig" . | nindent 8 }}

      root_keys:
        keys:
        - key: ${DISCOVERY_ROOT_KEY}
          account: root-key-discovery@aserto.com

      override:
        - methods:
            - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
            - /grpc.reflection.v1.ServerReflection.ServerReflectionInfo
            - /aserto.common.info.v1.Info/Info
          authenticators_enabled:
            anonymous: true
