{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.database.reader.credentialsSecret -}}
{{- if empty $secret | or (include "aserto-lib.isManagedResource" (list $secret .Release.Name) | eq "true") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.reader.credentialsSecret }}
data:
{{- if ($secret).data }}
  username: {{ $secret.data.username }}
  password: {{ $secret.data.password }}
{{- else }}
  username: {{ "controller_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc}}
{{- end }}
{{- end }}
