{{- $rootSecret := lookup "v1" "Secret" .Release.Namespace .Values.database.reader.credentialsSecret -}}
{{- if empty $rootSecret | or (include "aserto-lib.isManagedResource" (list $rootSecret .Release.Name) | eq "true") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.reader.credentialsSecret }}
data:
{{- if ($rootSecret).data }}
  username: {{ $rootSecret.data.username }}
  password: {{ $rootSecret.data.password }}
{{- else }}
  username: {{ "root_reader" | b64enc }}
  password: {{ randAlphaNum 20 | b64enc}}
{{- end }}
{{- end }}
