apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ include "aserto-lib.httpsPort" . }}
      targetPort: https
    - name: grpc
      port: {{ include "aserto-lib.grpcPort" . }}
      targetPort: grpc
    - name: metrics
      port: {{ include "aserto-lib.metricsPort" . }}
      targetPort: metrics
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
